"""empty message

Revision ID: 03152f265ddd
Revises: a1979c8b673f
Create Date: 2025-06-12 10:42:19.912008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03152f265ddd'
down_revision = 'a1979c8b673f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersalarydetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empId', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('present', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('absent', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('basicSalary', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('deductions', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('finalPay', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('mode', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('payslip', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('approvedLeaves', sa.String(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersalarydetails', schema=None) as batch_op:
        batch_op.drop_column('approvedLeaves')
        batch_op.drop_column('payslip')
        batch_op.drop_column('status')
        batch_op.drop_column('mode')
        batch_op.drop_column('finalPay')
        batch_op.drop_column('deductions')
        batch_op.drop_column('basicSalary')
        batch_op.drop_column('absent')
        batch_op.drop_column('present')
        batch_op.drop_column('empId')

    # ### end Alembic commands ###
