"""empty message

Revision ID: 038a4adbdf3a
Revises: a07045c9535b
Create Date: 2025-06-13 17:56:27.525693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '038a4adbdf3a'
down_revision = 'a07045c9535b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        # batch_op.alter_column('adminPanelId',
        #        existing_type=mysql.INTEGER(),
        #        nullable=False)
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.alter_column('adminPanelId',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
