"""empty message

Revision ID: 03fb0b8e1c30
Revises: eec14ad0b4a9
Create Date: 2025-06-17 14:43:22.507303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03fb0b8e1c30'
down_revision = 'eec14ad0b4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('shiftAndTimeManagement',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('shiftName', sa.String(length=120), nullable=False),
    # sa.Column('shiftType', mysql.ENUM('dayshift', 'nightshift'), nullable=False),
    # sa.Column('shiftStatus', sa.Boolean(), nullable=True),
    # sa.Column('shiftStart', sa.DateTime(), nullable=False),
    # sa.Column('shiftEnd', sa.DateTime(), nullable=False),
    # sa.Column('GraceTime', sa.DateTime(), nullable=False),
    # sa.Column('MaxEarly', sa.DateTime(), nullable=False),
    # sa.Column('MaxLateEntry', sa.DateTime(), nullable=False),
    # sa.Column('HalfDayThreshhold', sa.DateTime(), nullable=False),
    # sa.Column('OverTimeCountAfter', sa.DateTime(), nullable=False),
    # sa.Column('Biometric', sa.Boolean(), nullable=True),
    # sa.Column('RemoteCheckIn', sa.Boolean(), nullable=True),
    # sa.Column('ShiftSwap', sa.Boolean(), nullable=True),
    # sa.Column('superpanel', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['superpanel'], ['superadminpanel.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.drop_table('shiftandtimemanagement')
    with op.batch_alter_table('remotepolicy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remoteStatus', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('superPanel', sa.Integer(), nullable=False))
        batch_op.alter_column('allowed_department',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'superadminpanel', ['superPanel'], ['id'])
        batch_op.drop_column('shiftName')
        batch_op.drop_column('apply')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remotepolicy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apply', mysql.ENUM('employeementtype'), nullable=True))
        batch_op.add_column(sa.Column('shiftName', mysql.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('allowed_department',
               existing_type=sa.String(length=120),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
        batch_op.drop_column('superPanel')
        batch_op.drop_column('remoteStatus')

    op.create_table('shiftandtimemanagement',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shiftName', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('shiftType', mysql.ENUM('dayshift', 'nightshift'), nullable=False),
    sa.Column('shiftStatus', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('shiftStart', mysql.DATETIME(), nullable=False),
    sa.Column('shiftEnd', mysql.DATETIME(), nullable=False),
    sa.Column('GraceTime', mysql.DATETIME(), nullable=False),
    sa.Column('MaxEarly', mysql.DATETIME(), nullable=False),
    sa.Column('MaxLateEntry', mysql.DATETIME(), nullable=False),
    sa.Column('HalfDayThreshhold', mysql.DATETIME(), nullable=False),
    sa.Column('OverTimeCountAfter', mysql.DATETIME(), nullable=False),
    sa.Column('Biometric', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('RemoteCheckIn', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('ShiftSwap', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('superpanel', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['superpanel'], ['superadminpanel.id'], name=op.f('shiftandtimemanagement_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('shiftAndTimeManagement')
    # ### end Alembic commands ###
