"""empty message

Revision ID: 061f995b69d8
Revises: 094a9a2e7d45
Create Date: 2025-06-20 16:33:51.480919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061f995b69d8'
down_revision = '094a9a2e7d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskmanagement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskmanagement', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
