"""empty message

Revision ID: 0fc893204041
Revises: 
Create Date: 2025-06-17 17:09:29.176955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc893204041'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrollpolicy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policyname', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrollpolicy', schema=None) as batch_op:
        batch_op.drop_column('policyname')

    # ### end Alembic commands ###
