"""empty message

Revision ID: 0ff07453115c
Revises: 5f2c03049a5e
Create Date: 2025-06-19 10:24:15.299911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff07453115c'
down_revision = '5f2c03049a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userPanelId', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'userpaneldata', ['userPanelId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskuser', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_completed')
        batch_op.drop_column('userPanelId')

    # ### end Alembic commands ###
