"""empty message

Revision ID: 13c3acae8418
Revises: 2fb207cc6097
Create Date: 2025-06-15 09:18:11.878010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c3acae8418'
down_revision = '2fb207cc6097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userleave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unpaidDays', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userleave', schema=None) as batch_op:
        batch_op.drop_column('unpaidDays')

    # ### end Alembic commands ###
