"""empty message

Revision ID: 249df5a8e942
Revises: 13c3acae8418
Create Date: 2025-06-15 20:51:21.333584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249df5a8e942'
down_revision = '13c3acae8418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminleave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_leave_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminleave', schema=None) as batch_op:
        batch_op.drop_column('monthly_leave_limit')

    # ### end Alembic commands ###
