"""empty message

Revision ID: 27e5f3e7c527
Revises: d8375b08eaed
Create Date: 2025-06-10 13:11:51.613006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e5f3e7c527'
down_revision = 'd8375b08eaed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('problem', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userticket', schema=None) as batch_op:
        batch_op.drop_column('department')
        batch_op.drop_column('problem')

    # ### end Alembic commands ###
