"""empty message

Revision ID: 2adc73a32611
Revises: 061f995b69d8
Create Date: 2025-06-20 17:26:13.790620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2adc73a32611'
down_revision = '061f995b69d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskmanagement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskmanagement', schema=None) as batch_op:
        batch_op.drop_column('done')

    # ### end Alembic commands ###
