"""empty message

Revision ID: 2d0a5faba56d
Revises: 7920189a8a1b
Create Date: 2025-06-19 17:07:03.840768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d0a5faba56d'
down_revision = '7920189a8a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admindetail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legalCompanyName', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('headOffice', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('zipCode', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))
        batch_op.drop_column('legalName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admindetail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legalName', mysql.VARCHAR(length=250), nullable=True))
        batch_op.drop_column('location')
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('zipCode')
        batch_op.drop_column('state')
        batch_op.drop_column('headOffice')
        batch_op.drop_column('legalCompanyName')

    # ### end Alembic commands ###
