"""empty message

Revision ID: 2da0c1133146
Revises: 6f5660d22012
Create Date: 2025-06-13 17:43:06.971112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2da0c1133146'
down_revision = '6f5660d22012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        # batch_op.alter_column('adminPanelId',
        #        existing_type=mysql.INTEGER(),
        #        nullable=False)
        batch_op.drop_constraint(batch_op.f('announcement_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'superadminpanel', ['adminPanelId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('announcement_ibfk_1'), 'userpaneldata', ['adminPanelId'], ['id'])
        batch_op.alter_column('adminPanelId',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
