"""empty message

Revision ID: 2fb207cc6097
Revises: c035c0015a43
Create Date: 2025-06-14 20:25:53.336736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fb207cc6097'
down_revision = 'c035c0015a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userleave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days', sa.Integer(), nullable=True))
        batch_op.drop_column('month')
        batch_op.drop_column('attachment')
        batch_op.drop_column('day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userleave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('attachment', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('month', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('days')

    # ### end Alembic commands ###
