"""empty message

Revision ID: 340c275ce394
Revises: 86499fa5cb07
Create Date: 2025-06-13 17:41:45.563605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '340c275ce394'
down_revision = '86499fa5cb07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('announcement_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('userPanelId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userPanelId', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('announcement_ibfk_2'), 'superadminpanel', ['userPanelId'], ['id'])

    # ### end Alembic commands ###
