"""fixed table

Revision ID: 35e8baa54209
Revises: 6392c738ecf4
Create Date: 2025-06-14 19:08:02.415507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35e8baa54209'
down_revision = '6392c738ecf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminleave', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('leaveStatus', sa.Enum('paid', 'unpaid', name='leave_status_enum'), nullable=False))
        # batch_op.add_column(sa.Column('calculationType', sa.Enum('monthly', 'quarterly', 'annually', name='leave_calculation_type'), nullable=False))
        # batch_op.add_column(sa.Column('day_type', sa.Enum('fullday', 'halfday', name='day_type_enum'), nullable=False))
        # batch_op.add_column(sa.Column('probation', sa.Boolean(), nullable=True))
        # batch_op.add_column(sa.Column('carryforward', sa.Boolean(), nullable=True))
        # batch_op.add_column(sa.Column('encashment', sa.Boolean(), nullable=True))
        # batch_op.alter_column('leaveType',
            #    existing_type=mysql.VARCHAR(length=120),
            #    type_=sa.Enum('casual', 'sick', name='leave_type_enum'),
            #    nullable=False)
        batch_op.drop_column('Quota')
        batch_op.drop_column('carryForward')
        batch_op.drop_column('LeaveStatus')
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminleave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('LeaveStatus', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('carryForward', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Quota', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('leaveType',
               existing_type=sa.Enum('casual', 'sick', name='leave_type_enum'),
               type_=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('encashment')
        batch_op.drop_column('carryforward')
        batch_op.drop_column('probation')
        batch_op.drop_column('day_type')
        batch_op.drop_column('calculationType')
        batch_op.drop_column('leaveStatus')

    # ### end Alembic commands ###
