"""empty message

Revision ID: 381593278c78
Revises: 65bd9ac10114
Create Date: 2025-06-23 16:25:53.855963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381593278c78'
down_revision = '65bd9ac10114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_password', sa.String(length=120), nullable=False))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('master', schema=None) as batch_op:
        batch_op.drop_column('company_password')

    # ### end Alembic commands ###
