"""empty message

Revision ID: 408566e05aba
Revises: fc7efbdee066
Create Date: 2025-06-13 15:55:43.922118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408566e05aba'
down_revision = 'fc7efbdee066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_column('published')

    # ### end Alembic commands ###
