"""empty message

Revision ID: 458a041f5c35
Revises: 038a4adbdf3a
Create Date: 2025-06-13 18:00:44.684350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '458a041f5c35'
down_revision = '038a4adbdf3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        # batch_op.alter_column('adminPanelId',
        #        existing_type=mysql.INTEGER(),
        #        nullable=False)
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.alter_column('adminPanelId',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
