"""empty message

Revision ID: 4e41177b8860
Revises: 7b191b02e8b4
Create Date: 2025-06-09 18:26:01.601542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e41177b8860'
down_revision = '7b191b02e8b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('superadmin_panel_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('superadmin_panel_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
