"""empty message

Revision ID: 5964d9cfe736
Revises: 72edde298dbd
Create Date: 2025-06-23 23:27:29.355042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5964d9cfe736'
down_revision = '72edde298dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        batch_op.drop_column('master_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('master_id', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
