"""empty message

Revision ID: 5f2c03049a5e
Revises: 9032f282692c
Create Date: 2025-06-18 16:11:31.212844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f2c03049a5e'
down_revision = '9032f282692c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('senderID',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('recieverID',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('recieverID',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('senderID',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
