"""empty message

Revision ID: 60a6dda7296f
Revises: 8bd1889a3a1e
Create Date: 2025-06-19 12:58:29.011188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a6dda7296f'
down_revision = '8bd1889a3a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_estabilish', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('company_years', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        batch_op.drop_column('company_years')
        batch_op.drop_column('company_estabilish')

    # ### end Alembic commands ###
