"""empty message

Revision ID: 65bd9ac10114
Revises: e39a7b5b1f24
Create Date: 2025-06-23 11:58:54.221941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65bd9ac10114'
down_revision = 'e39a7b5b1f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shiftandtimemanagement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workingDays', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('saturdayCondition', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shiftandtimemanagement', schema=None) as batch_op:
        batch_op.drop_column('saturdayCondition')
        batch_op.drop_column('workingDays')

    # ### end Alembic commands ###
