"""empty message

Revision ID: 696c21f1d017
Revises: 03fb0b8e1c30
Create Date: 2025-06-17 14:45:30.984289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '696c21f1d017'
down_revision = '03fb0b8e1c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('shiftAndTimeManagement',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('shiftName', sa.String(length=120), nullable=False),
    # sa.Column('shiftType', mysql.ENUM('dayshift', 'nightshift'), nullable=False),
    # sa.Column('shiftStatus', sa.Boolean(), nullable=True),
    # sa.Column('shiftStart', sa.DateTime(), nullable=False),
    # sa.Column('shiftEnd', sa.DateTime(), nullable=False),
    # sa.Column('GraceTime', sa.DateTime(), nullable=False),
    # sa.Column('MaxEarly', sa.DateTime(), nullable=False),
    # sa.Column('MaxLateEntry', sa.DateTime(), nullable=False),
    # sa.Column('HalfDayThreshhold', sa.DateTime(), nullable=False),
    # sa.Column('OverTimeCountAfter', sa.DateTime(), nullable=False),
    # sa.Column('Biometric', sa.Boolean(), nullable=True),
    # sa.Column('RemoteCheckIn', sa.Boolean(), nullable=True),
    # sa.Column('ShiftSwap', sa.Boolean(), nullable=True),
    # sa.Column('superpanel', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['superpanel'], ['superadminpanel.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.drop_table('shiftandtimemanagement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shiftandtimemanagement',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shiftName', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('shiftType', mysql.ENUM('dayshift', 'nightshift'), nullable=False),
    sa.Column('shiftStatus', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('shiftStart', mysql.DATETIME(), nullable=False),
    sa.Column('shiftEnd', mysql.DATETIME(), nullable=False),
    sa.Column('GraceTime', mysql.DATETIME(), nullable=False),
    sa.Column('MaxEarly', mysql.DATETIME(), nullable=False),
    sa.Column('MaxLateEntry', mysql.DATETIME(), nullable=False),
    sa.Column('HalfDayThreshhold', mysql.DATETIME(), nullable=False),
    sa.Column('OverTimeCountAfter', mysql.DATETIME(), nullable=False),
    sa.Column('Biometric', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('RemoteCheckIn', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('ShiftSwap', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('superpanel', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['superpanel'], ['superadminpanel.id'], name=op.f('shiftandtimemanagement_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('shiftAndTimeManagement')
    # ### end Alembic commands ###
