"""empty message

Revision ID: 6f5660d22012
Revises: 340c275ce394
Create Date: 2025-06-13 17:42:10.624022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f5660d22012'
down_revision = '340c275ce394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_column('userId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
