"""empty message

Revision ID: 72edde298dbd
Revises: 8ecbc9db0667
Create Date: 2025-06-23 23:13:31.987784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72edde298dbd'
down_revision = '8ecbc9db0667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        # batch_op.alter_column('master_id',
        #        existing_type=mysql.INTEGER(),
        #        nullable=True)
        # batch_op.create_foreign_key(None, 'master', ['master_id'], ['id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('master_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
