"""empty message

Revision ID: 75b1d4dbbfd2
Revises: 0902bca3e10e
Create Date: 2025-06-09 12:02:54.895695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b1d4dbbfd2'
down_revision = '0902bca3e10e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['managerId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_ibfk_3'), 'superadmin', ['managerId'], ['id'])

    # ### end Alembic commands ###
