"""empty message

Revision ID: 7920189a8a1b
Revises: 
Create Date: 2025-06-19 14:54:43.503557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7920189a8a1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        batch_op.alter_column('company_type',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('company_website',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('company_years',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('birthday')

    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        batch_op.alter_column('company_years',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('company_website',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('company_type',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
