"""empty message

Revision ID: 7b191b02e8b4
Revises: 75b1d4dbbfd2
Create Date: 2025-06-09 17:28:05.302511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b191b02e8b4'
down_revision = '75b1d4dbbfd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('onBoardingStatus',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('currentSalary',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('currentSalary',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('onBoardingStatus',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
