"""empty message

Revision ID: 82cd9e41fb3d
Revises: 8c0b131de13c
Create Date: 2025-06-16 11:42:35.018538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cd9e41fb3d'
down_revision = '8c0b131de13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminleave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leaveName', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminleave', schema=None) as batch_op:
        batch_op.drop_column('leaveName')

    # ### end Alembic commands ###
