"""empty message

Revision ID: 86499fa5cb07
Revises: 8a5089224272
Create Date: 2025-06-13 16:07:44.643695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86499fa5cb07'
down_revision = '8a5089224272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
