"""empty message

Revision ID: 8a5089224272
Revises: 408566e05aba
Create Date: 2025-06-13 16:02:15.877604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a5089224272'
down_revision = '408566e05aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('adminPanelId', sa.Integer(), nullable=True))
        # batch_op.add_column(sa.Column('userPanelId', sa.Integer(), nullable=True))
        # batch_op.alter_column('userId',
        #        existing_type=mysql.INTEGER(),
        #        type_=sa.String(length=255),
        #        nullable=True)
        batch_op.drop_constraint(batch_op.f('announcement_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'userpaneldata', ['adminPanelId'], ['id'])
        batch_op.create_foreign_key(None, 'superadminpanel', ['userPanelId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('announcement_ibfk_1'), 'user', ['userId'], ['id'])
        # batch_op.alter_column('userId',
        #        existing_type=sa.String(length=255),
        #        type_=mysql.INTEGER(),
        #        nullable=False)
        batch_op.drop_column('userPanelId')
        batch_op.drop_column('adminPanelId')

    # ### end Alembic commands ###
