"""empty message

Revision ID: 8bd1889a3a1e
Revises: 0ff07453115c
Create Date: 2025-06-19 12:11:09.993513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8bd1889a3a1e'
down_revision = '0ff07453115c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('empId',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('empId',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
