"""empty message

Revision ID: 8c0b131de13c
Revises: 249df5a8e942
Create Date: 2025-06-16 11:39:29.608471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c0b131de13c'
down_revision = '249df5a8e942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminleave', schema=None) as batch_op:
        batch_op.drop_column('leaveStatus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminleave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leaveStatus', mysql.ENUM('paid', 'unpaid'), nullable=False))

    # ### end Alembic commands ###
