"""empty message

Revision ID: 91dfd9f87710
Revises: 82cd9e41fb3d
Create Date: 2025-06-16 13:02:18.052003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91dfd9f87710'
down_revision = '82cd9e41fb3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userleave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userleave', schema=None) as batch_op:
        batch_op.drop_column('createdAt')

    # ### end Alembic commands ###
