"""empty message

Revision ID: 9d7766868408
Revises: 9d973b826df5
Create Date: 2025-06-16 16:41:29.038467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7766868408'
down_revision = '9d973b826df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('punchdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('punchdata', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
