"""empty message

Revision ID: 9d973b826df5
Revises: b6758d8f249d
Create Date: 2025-06-16 15:22:02.901885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d973b826df5'
down_revision = 'b6758d8f249d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonuspolicy', schema=None) as batch_op:
        batch_op.drop_column('bonus_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonuspolicy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_description', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
