"""empty message

Revision ID: 9f9a4f3c82a2
Revises: 2d0a5faba56d
Create Date: 2025-06-20 10:19:56.849862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f9a4f3c82a2'
down_revision = '2d0a5faba56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productasset', schema=None) as batch_op:
        batch_op.alter_column('productId',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('productName',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('qty',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('purchaseDate',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('condition',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productasset', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('condition',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('purchaseDate',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('qty',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('productName',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('productId',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
