"""empty message

Revision ID: a07045c9535b
Revises: 380b5cfd5df3
Create Date: 2025-06-13 17:52:19.488469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a07045c9535b'
down_revision = '380b5cfd5df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        # batch_op.alter_column('adminPanelId',
        #        existing_type=mysql.INTEGER(),
        #        nullable=False)
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.alter_column('adminPanelId',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
