"""empty message

Revision ID: a0eb7bb8e882
Revises: 
Create Date: 2025-06-09 10:33:49.189086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0eb7bb8e882'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('userRole',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('user_ibfk_1'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('user_ibfk_1'), 'role', ['userRole'], ['id'])
        batch_op.alter_column('userRole',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               nullable=True)

    op.create_table('role',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('roleAssigned', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
