"""initial clean migration

Revision ID: a1979c8b673f
Revises: 
Create Date: 2025-06-11 17:33:26.979382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1979c8b673f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdocument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('panelDataID', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'userpaneldata', ['panelDataID'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdocument', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('panelDataID')

    # ### end Alembic commands ###
