"""empty message

Revision ID: b6758d8f249d
Revises: 91dfd9f87710
Create Date: 2025-06-16 14:10:24.594066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6758d8f249d'
down_revision = '91dfd9f87710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonuspolicy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_method', mysql.ENUM('fixed', 'percentage'), nullable=False))
        batch_op.add_column(sa.Column('apply', mysql.ENUM('employee', 'employeementType', 'department'), nullable=False))
        batch_op.add_column(sa.Column('employeement_type', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('department_type', sa.String(length=120), nullable=True))
        batch_op.alter_column('bonus_description',
               existing_type=mysql.ENUM('fixed', 'percentage'),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonuspolicy', schema=None) as batch_op:
        batch_op.alter_column('bonus_description',
               existing_type=sa.String(length=255),
               type_=mysql.ENUM('fixed', 'percentage'),
               existing_nullable=False)
        batch_op.drop_column('department_type')
        batch_op.drop_column('employeement_type')
        batch_op.drop_column('apply')
        batch_op.drop_column('bonus_method')

    # ### end Alembic commands ###
