"""empty message

Revision ID: bd7a2ef79909
Revises: ef73a911f909
Create Date: 2025-06-22 19:37:01.899906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7a2ef79909'
down_revision = 'ef73a911f909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userpromotion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empId', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('previous_department', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('new_department', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dateofpromotion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userpromotion', schema=None) as batch_op:
        batch_op.drop_column('dateofpromotion')
        batch_op.drop_column('description')
        batch_op.drop_column('new_department')
        batch_op.drop_column('previous_department')
        batch_op.drop_column('empId')

    # ### end Alembic commands ###
