"""empty message

Revision ID: bf515acb225b
Revises: 0fc893204041
Create Date: 2025-06-18 11:06:31.295276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf515acb225b'
down_revision = '0fc893204041'
branch_labels = None
depends_on = None


def upgrade():
    # ### Drop foreign keys before dropping pollvote ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Drop foreign key constraints from pollvote if exist
    fk_names = [fk['name'] for fk in inspector.get_foreign_keys('pollvote') if fk['name']]
    for fk_name in fk_names:
        op.drop_constraint(fk_name, 'pollvote', type_='foreignkey')

    # Drop index
    with op.batch_alter_table('pollvote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_user_option_vote'))

    # Drop tables
    op.drop_table('pollvote')
    op.drop_table('polloption')

    # Alter announcement table
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('scheduled_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('poll_question', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('poll_option_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('poll_option_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('poll_option_3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('poll_option_4', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('votes_option_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('votes_option_2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('votes_option_3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('votes_option_4', sa.Integer(), nullable=True))
        batch_op.drop_column('pollQuestion')
        batch_op.drop_column('published')
        batch_op.drop_column('scheduleTime')
        batch_op.drop_column('videoURL')
        batch_op.drop_column('createdAt')
        batch_op.drop_column('imageURL')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageURL', mysql.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('createdAt', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('videoURL', mysql.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('scheduleTime', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('published', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pollQuestion', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('votes_option_4')
        batch_op.drop_column('votes_option_3')
        batch_op.drop_column('votes_option_2')
        batch_op.drop_column('votes_option_1')
        batch_op.drop_column('poll_option_4')
        batch_op.drop_column('poll_option_3')
        batch_op.drop_column('poll_option_2')
        batch_op.drop_column('poll_option_1')
        batch_op.drop_column('poll_question')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_published')
        batch_op.drop_column('scheduled_time')
        batch_op.drop_column('title')

    op.create_table('polloption',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('announcementID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('optionText', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('voteCount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['announcementID'], ['announcement.id'], name='polloption_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pollvote',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('optionID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['optionID'], ['polloption.id'], name=op.f('pollvote_ibfk_2')),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], name=op.f('pollvote_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('pollvote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_user_option_vote'), ['userID', 'optionID'], unique=True)

    # ### end Alembic commands ###
