"""fixed table

Revision ID: c035c0015a43
Revises: d177cc715868
Create Date: 2025-06-14 20:16:19.079871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c035c0015a43'
down_revision = 'd177cc715868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userleavequota')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userleavequota',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('leaveType', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('definedYearlyLeave', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definedMonthlyLeave', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('monthOfLeave', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_leave_taken', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remaining_leave', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
