"""empty message

Revision ID: c0ca651712a7
Revises: a0eb7bb8e882
Create Date: 2025-06-09 11:37:16.624275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ca651712a7'
down_revision = 'a0eb7bb8e882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superId', sa.String(length=120), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'superadmin', ['managerId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        batch_op.drop_column('superId')

    # ### end Alembic commands ###
