"""empty message

Revision ID: d177cc715868
Revises: 7a5407495468
Create Date: 2025-06-14 19:53:09.677133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd177cc715868'
down_revision = '7a5407495468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminleave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lapse_policy', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('max_leave_once', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_leave_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminleave', schema=None) as batch_op:
        batch_op.drop_column('max_leave_year')
        batch_op.drop_column('max_leave_once')
        batch_op.drop_column('lapse_policy')

    # ### end Alembic commands ###
