"""empty message

Revision ID: d1a3f829ecc8
Revises: c0ca651712a7
Create Date: 2025-06-09 11:55:16.953651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a3f829ecc8'
down_revision = 'c0ca651712a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superadminId', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('superadminId')

    # ### end Alembic commands ###
