"""empty message

Revision ID: df7589756b74
Revises: e7ce75da744f
Create Date: 2025-06-20 14:10:33.538801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7589756b74'
down_revision = 'e7ce75da744f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productasset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productasset', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
