"""empty message

Revision ID: e39a7b5b1f24
Revises: f5e18040a88e
Create Date: 2025-06-22 20:38:21.899694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e39a7b5b1f24'
down_revision = 'f5e18040a88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersalarydetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bonus_reason', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersalarydetails', schema=None) as batch_op:
        batch_op.drop_column('bonus_reason')
        batch_op.drop_column('bonus')

    # ### end Alembic commands ###
