"""empty message

Revision ID: e7ce75da744f
Revises: 9f9a4f3c82a2
Create Date: 2025-06-20 11:15:22.189805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ce75da744f'
down_revision = '9f9a4f3c82a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminholiday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminholiday', schema=None) as batch_op:
        batch_op.drop_column('is_enabled')

    # ### end Alembic commands ###
