"""empty message

Revision ID: ef73a911f909
Revises: f7d2ca47431f
Create Date: 2025-06-22 19:26:19.332136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef73a911f909'
down_revision = 'f7d2ca47431f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userpromotion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userpanel', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'userpaneldata', ['userpanel'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userpromotion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('userpanel')

    # ### end Alembic commands ###
