"""empty message

Revision ID: f2eada4a8df8
Revises: bd7a2ef79909
Create Date: 2025-06-22 20:07:26.957146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2eada4a8df8'
down_revision = 'bd7a2ef79909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersalarydetails', schema=None) as batch_op:
        batch_op.alter_column('payslip',
               existing_type=mysql.VARCHAR(length=12),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersalarydetails', schema=None) as batch_op:
        batch_op.alter_column('payslip',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=12),
               existing_nullable=True)

    # ### end Alembic commands ###
