"""empty message

Revision ID: f5e18040a88e
Revises: f2eada4a8df8
Create Date: 2025-06-22 20:10:23.215262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e18040a88e'
down_revision = 'f2eada4a8df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersalarydetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onhold', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('onhold_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersalarydetails', schema=None) as batch_op:
        batch_op.drop_column('createdAt')
        batch_op.drop_column('onhold_reason')
        batch_op.drop_column('onhold')

    # ### end Alembic commands ###
