"""empty message

Revision ID: f65e6948ea38
Revises: 03152f265ddd
Create Date: 2025-06-12 10:59:54.354297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65e6948ea38'
down_revision = '03152f265ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminleave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superadminPanel', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'superadminpanel', ['superadminPanel'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminleave', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('superadminPanel')

    # ### end Alembic commands ###
