"""empty message

Revision ID: f7d2ca47431f
Revises: 2adc73a32611
Create Date: 2025-06-20 22:02:45.906988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d2ca47431f'
down_revision = '2adc73a32611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_empId', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userticket', schema=None) as batch_op:
        batch_op.drop_column('assigned_to_empId')

    # ### end Alembic commands ###
