"""empty message

Revision ID: fdb98d34b9f6
Revises: 45fc777ef454
Create Date: 2025-06-18 11:51:20.123485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdb98d34b9f6'
down_revision = '45fc777ef454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
